spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-cherry-665397.eu-central-1.aws.neon.tech/spring-ecommerce-api?user=lptrk&password=2kNRwvGeJD8x
    username: lptrk
    password: 2kNRwvGeJD8x
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
